publish development servercore1809 helper docker image:
  extends:
  - .windows1809
  - .rules:release:development:merge-requests
  - .windows_docker_images
  stage: windows helper images
  variables:
    PUSH_TO_ECR_PUBLIC: "false"
  retry: 2

publish development servercore2004 helper docker image:
  extends:
  - .windows2004
  - .rules:release:development:merge-requests
  - .windows_docker_images
  stage: windows helper images
  variables:
    PUSH_TO_ECR_PUBLIC: "false"
  retry: 2

publish development servercore20H2 helper docker image:
  extends:
  - .windows2004
  - .rules:release:development:merge-requests
  - .windows_docker_images
  stage: windows helper images
  variables:
    PUSH_TO_ECR_PUBLIC: "false"
  retry: 2

publish development servercore21H1 helper docker image:
  extends:
  - .windows21H1
  - .rules:release:development:merge-requests
  - .windows_docker_images
  stage: windows helper images
  variables:
    PUSH_TO_ECR_PUBLIC: "false"
  retry: 2
